
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox5;
	private global::Gtk.Frame frame5;
	private global::Gtk.VBox vbox7;
	private global::Gtk.Alignment GtkAlignment;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Label label13;
	private global::Gtk.SpinButton spinbutton3;
	private global::Gtk.Alignment GtkAlignment1;
	private global::Gtk.HBox hbox3;
	private global::Gtk.Label label14;
	private global::Gtk.SpinButton spinbutton4;
	private global::Gtk.Label GtkLabel;
	private global::Gtk.Frame frame7;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.TreeView listView;
	private global::Gtk.Label GtkLabel1;
	private global::Gtk.Frame frame8;
	private global::Gtk.HBox hbox4;
	private global::Gtk.Alignment alignment3;
	private global::Gtk.VBox vbox8;
	private global::Gtk.HBox hbox5;
	private global::Gtk.Label label15;
	private global::Gtk.Label labMax;
	private global::Gtk.HBox hbox6;
	private global::Gtk.Label label16;
	private global::Gtk.Label labQueue;
	private global::Gtk.HBox hbox7;
	private global::Gtk.Label label17;
	private global::Gtk.Label labRunning;
	private global::Gtk.HBox hbox8;
	private global::Gtk.Label label18;
	private global::Gtk.Label labComplated;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView textview3;
	private global::Gtk.Label GtkLabel2;
	private global::Gtk.HBox hbox9;
	private global::Gtk.Button button9;
	private global::Gtk.Button button10;
	private global::Gtk.Button button11;
	private global::Gtk.Button button12;
	private global::Gtk.Button button13;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Task framework test for Mono");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.frame5 = new global::Gtk.Frame ();
		this.frame5.Name = "frame5";
		this.frame5.ShadowType = ((global::Gtk.ShadowType)(1));
		this.frame5.LabelXalign = 0.01F;
		// Container child frame5.Gtk.Container+ContainerChild
		this.vbox7 = new global::Gtk.VBox ();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label13 = new global::Gtk.Label ();
		this.label13.WidthRequest = 73;
		this.label13.Name = "label13";
		this.label13.Xpad = 20;
		this.label13.Xalign = 0F;
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Total:");
		this.label13.Justify = ((global::Gtk.Justification)(1));
		this.hbox2.Add (this.label13);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label13]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.spinbutton3 = new global::Gtk.SpinButton (0D, 100D, 1D);
		this.spinbutton3.WidthRequest = 162;
		this.spinbutton3.CanFocus = true;
		this.spinbutton3.Name = "spinbutton3";
		this.spinbutton3.Adjustment.PageIncrement = 10D;
		this.spinbutton3.ClimbRate = 1D;
		this.spinbutton3.Numeric = true;
		this.spinbutton3.Value = 10D;
		this.hbox2.Add (this.spinbutton3);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.spinbutton3]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.GtkAlignment.Add (this.hbox2);
		this.vbox7.Add (this.GtkAlignment);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.GtkAlignment]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label14 = new global::Gtk.Label ();
		this.label14.WidthRequest = 73;
		this.label14.Name = "label14";
		this.label14.Xpad = 20;
		this.label14.Xalign = 0F;
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Parallel:");
		this.label14.Justify = ((global::Gtk.Justification)(1));
		this.hbox3.Add (this.label14);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label14]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.spinbutton4 = new global::Gtk.SpinButton (0D, 100D, 1D);
		this.spinbutton4.WidthRequest = 162;
		this.spinbutton4.CanFocus = true;
		this.spinbutton4.Name = "spinbutton4";
		this.spinbutton4.Adjustment.PageIncrement = 10D;
		this.spinbutton4.ClimbRate = 1D;
		this.spinbutton4.Numeric = true;
		this.spinbutton4.Value = 3D;
		this.hbox3.Add (this.spinbutton4);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.spinbutton4]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		this.GtkAlignment1.Add (this.hbox3);
		this.vbox7.Add (this.GtkAlignment1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.GtkAlignment1]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		this.frame5.Add (this.vbox7);
		this.GtkLabel = new global::Gtk.Label ();
		this.GtkLabel.Name = "GtkLabel";
		this.GtkLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Task Setting</b>");
		this.GtkLabel.UseMarkup = true;
		this.frame5.LabelWidget = this.GtkLabel;
		this.vbox5.Add (this.frame5);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.frame5]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.frame7 = new global::Gtk.Frame ();
		this.frame7.Name = "frame7";
		this.frame7.ShadowType = ((global::Gtk.ShadowType)(1));
		this.frame7.LabelXalign = 0.01F;
		this.frame7.BorderWidth = ((uint)(1));
		// Container child frame7.Gtk.Container+ContainerChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.listView = new global::Gtk.TreeView ();
		this.listView.CanFocus = true;
		this.listView.Name = "listView";
		this.listView.EnableSearch = false;
		this.GtkScrolledWindow1.Add (this.listView);
		this.frame7.Add (this.GtkScrolledWindow1);
		this.GtkLabel1 = new global::Gtk.Label ();
		this.GtkLabel1.Name = "GtkLabel1";
		this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Task List</b>");
		this.GtkLabel1.UseMarkup = true;
		this.frame7.LabelWidget = this.GtkLabel1;
		this.vbox5.Add (this.frame7);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.frame7]));
		w13.Position = 1;
		// Container child vbox5.Gtk.Box+BoxChild
		this.frame8 = new global::Gtk.Frame ();
		this.frame8.HeightRequest = 167;
		this.frame8.Name = "frame8";
		this.frame8.ShadowType = ((global::Gtk.ShadowType)(1));
		this.frame8.LabelXalign = 0.01F;
		this.frame8.BorderWidth = ((uint)(1));
		// Container child frame8.Gtk.Container+ContainerChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.alignment3 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment3.Name = "alignment3";
		// Container child alignment3.Gtk.Container+ContainerChild
		this.vbox8 = new global::Gtk.VBox ();
		this.vbox8.WidthRequest = 143;
		this.vbox8.Name = "vbox8";
		this.vbox8.Homogeneous = true;
		this.vbox8.Spacing = 22;
		this.vbox8.BorderWidth = ((uint)(1));
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label15 = new global::Gtk.Label ();
		this.label15.WidthRequest = 85;
		this.label15.Name = "label15";
		this.label15.Xpad = 20;
		this.label15.Xalign = 0F;
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Max:");
		this.hbox5.Add (this.label15);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label15]));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.labMax = new global::Gtk.Label ();
		this.labMax.Name = "labMax";
		this.labMax.LabelProp = "0";
		this.hbox5.Add (this.labMax);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.labMax]));
		w15.Position = 1;
		w15.Expand = false;
		w15.Fill = false;
		this.vbox8.Add (this.hbox5);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox5]));
		w16.Position = 0;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label16 = new global::Gtk.Label ();
		this.label16.WidthRequest = 85;
		this.label16.Name = "label16";
		this.label16.Xpad = 20;
		this.label16.Xalign = 0F;
		this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Queue:");
		this.hbox6.Add (this.label16);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label16]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.labQueue = new global::Gtk.Label ();
		this.labQueue.Name = "labQueue";
		this.labQueue.LabelProp = "0";
		this.hbox6.Add (this.labQueue);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.labQueue]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		this.vbox8.Add (this.hbox6);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox6]));
		w19.Position = 1;
		w19.Expand = false;
		w19.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.label17 = new global::Gtk.Label ();
		this.label17.WidthRequest = 85;
		this.label17.Xpad = 20;
		this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Running:");
		this.hbox7.Add (this.label17);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label17]));
		w20.Position = 0;
		w20.Expand = false;
		w20.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.labRunning = new global::Gtk.Label ();
		this.labRunning.Name = "labRunning";
		this.labRunning.LabelProp = "0";
		this.hbox7.Add (this.labRunning);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.labRunning]));
		w21.Position = 1;
		w21.Expand = false;
		w21.Fill = false;
		this.vbox8.Add (this.hbox7);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox7]));
		w22.Position = 2;
		w22.Expand = false;
		w22.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox ();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.label18 = new global::Gtk.Label ();
		this.label18.WidthRequest = 85;
		this.label18.Name = "label18";
		this.label18.Xpad = 20;
		this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Complated:");
		this.hbox8.Add (this.label18);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label18]));
		w23.Position = 0;
		w23.Expand = false;
		w23.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.labComplated = new global::Gtk.Label ();
		this.labComplated.Name = "labComplated";
		this.labComplated.LabelProp = "0";
		this.hbox8.Add (this.labComplated);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.labComplated]));
		w24.Position = 1;
		w24.Expand = false;
		w24.Fill = false;
		this.vbox8.Add (this.hbox8);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox8]));
		w25.Position = 3;
		w25.Expand = false;
		w25.Fill = false;
		this.alignment3.Add (this.vbox8);
		this.hbox4.Add (this.alignment3);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.alignment3]));
		w27.Position = 0;
		w27.Expand = false;
		w27.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview3 = new global::Gtk.TextView ();
		this.textview3.CanFocus = true;
		this.textview3.Name = "textview3";
		this.GtkScrolledWindow.Add (this.textview3);
		this.hbox4.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.GtkScrolledWindow]));
		w29.Position = 1;
		this.frame8.Add (this.hbox4);
		this.GtkLabel2 = new global::Gtk.Label ();
		this.GtkLabel2.Name = "GtkLabel2";
		this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Task Control</b>");
		this.GtkLabel2.UseMarkup = true;
		this.frame8.LabelWidget = this.GtkLabel2;
		this.vbox5.Add (this.frame8);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.frame8]));
		w31.Position = 2;
		w31.Expand = false;
		w31.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox ();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.button9 = new global::Gtk.Button ();
		this.button9.CanFocus = true;
		this.button9.Name = "button9";
		this.button9.UseUnderline = true;
		this.button9.Label = global::Mono.Unix.Catalog.GetString ("Run Test");
		this.hbox9.Add (this.button9);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.button9]));
		w32.Position = 0;
		w32.Expand = false;
		w32.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.button10 = new global::Gtk.Button ();
		this.button10.CanFocus = true;
		this.button10.Name = "button10";
		this.button10.UseUnderline = true;
		this.button10.Label = global::Mono.Unix.Catalog.GetString ("Stop");
		this.hbox9.Add (this.button10);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.button10]));
		w33.Position = 1;
		w33.Expand = false;
		w33.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.button11 = new global::Gtk.Button ();
		this.button11.CanFocus = true;
		this.button11.Name = "button11";
		this.button11.UseUnderline = true;
		this.button11.Label = global::Mono.Unix.Catalog.GetString ("Pause");
		this.hbox9.Add (this.button11);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.button11]));
		w34.Position = 2;
		w34.Expand = false;
		w34.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.button12 = new global::Gtk.Button ();
		this.button12.CanFocus = true;
		this.button12.Name = "button12";
		this.button12.UseUnderline = true;
		this.button12.Label = global::Mono.Unix.Catalog.GetString ("Resume");
		this.hbox9.Add (this.button12);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.button12]));
		w35.Position = 3;
		w35.Expand = false;
		w35.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.button13 = new global::Gtk.Button ();
		this.button13.CanFocus = true;
		this.button13.Name = "button13";
		this.button13.UseUnderline = true;
		this.button13.Label = global::Mono.Unix.Catalog.GetString ("Exit");
		this.hbox9.Add (this.button13);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.button13]));
		w36.Position = 4;
		w36.Expand = false;
		w36.Fill = false;
		this.vbox5.Add (this.hbox9);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox9]));
		w37.Position = 3;
		w37.Expand = false;
		w37.Fill = false;
		this.Add (this.vbox5);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 953;
		this.DefaultHeight = 720;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
